# Configuration Prometheus
*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus

# Correction du ConsoleSink (Optionnel, utile pour le debug)
*.sink.console.class=org.apache.spark.metrics.sink.ConsoleSink
*.sink.console.period=120
*.sink.console.unit=seconds