
id: main
namespace: sds.infra

variables:
  script_path: /app/scripts/

tasks:

# --- PHASE 1 : REDPANDA INITIALISATION ---
  - id: init_redpanda_topics
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "ocde-p12_sport-pipeline"
    containerImage: docker.redpanda.com/redpandadata/redpanda:v23.3.9
    allowFailure: true
    commands:
      # Topics creation for CDC and Spark
      - rpk topic create cdc.public.employees --brokers redpanda:9092
      - rpk topic create cdc.public.sports_activities --brokers redpanda:9092
    
  # --- PHASE 2 : DEBEZIUM INITIALISATION ---


  - id: register_cdc_connector
    type: io.kestra.plugin.core.http.Request
    uri: "http://debezium:8083/connectors/postgres-connector/config"
    method: PUT
    contentType: application/json
    body: |
      {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "database.hostname": "postgres",
        "database.port": "5432",
        "database.user": "{{ secret('POSTGRES_USER') }}",
        "database.password": "{{ secret('POSTGRES_PASSWORD') }}",
        "database.dbname": "{{ secret('POSTGRES_DB') }}",
        "database.server.name": "postgres",
        "table.include.list": "public.employees,public.sports_activities",
        "plugin.name": "pgoutput",
        "decimal.handling.mode": "double",
        "topic.prefix": "cdc"
      }

  - id: wait15_debezium
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT15S

  - id: launch_spark_stream
    type: io.kestra.plugin.core.flow.Parallel
    description: Launch the 3 spark stream readers
    tasks: 
    - id: spark_employees
      description: Read the CDC stream public employees
      type: io.kestra.plugin.core.flow.Subflow
      namespace: sds.infra
      flowId: spark_employees_stream
      wait: false
    
    - id: spark_activities_stats
      description: Read the CDC activities stream for statistics
      type: io.kestra.plugin.core.flow.Subflow
      namespace: sds.infra
      flowId: spark_activities_stats_stream
      wait: false

    - id: spark_activities_slack
      description: Read the CDC activities stream for slack posts
      type: io.kestra.plugin.core.flow.Subflow
      namespace: sds.infra
      flowId: spark_activities_slack_stream
      wait: false


  - id: check_hr
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: "jdbc:postgresql://postgres:5432/sport_app_db"
    username: "{{ secret('POSTGRES_USER') }}"
    password: "{{ secret('POSTGRES_PASSWORD') }}"
    sql: SELECT count(*) AS nb_emp FROM employees
    fetchType: FETCH_ONE


  - id: ingest_pipeline
    type: io.kestra.plugin.core.flow.Subflow
    namespace: sds.infra
    runIf: "{{ outputs.check_hr.row['nb_emp'] == 0 }}"
    flowId: ingest_hr
    wait: true

  - id: set_active_status
    type: io.kestra.plugin.core.kv.Set
    key: "spark_status"
    value: "active"

errors:
  - id: send_alert
    type: io.kestra.plugin.core.flow.Subflow
    flowId: notify_error
    namespace: sds.infra
    inputs:
      test: true
      message: "Main startup flow failed"

finally:
  - id: set_inactive_status
    type: io.kestra.plugin.core.kv.Set
    key: "spark_status"
    value: "inactive"

triggers:
  - id: auto_start
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"
    stopAfter:
      - SUCCESS


