id: notify
namespace: sds.infra
description: "Centralisation des alertes pour le namespace"
inputs:
  - id: test
    type: BOOL
    defaults: true

tasks:
  - id: check_test
    type: io.kestra.plugin.core.flow.If
    condition : "{{ inputs.test }}"
    then :
      - id: log_final
        type: io.kestra.plugin.core.log.Log
        message: |
          "{{inputs.message}}"
    else:
      - id: notify_slack
        type: io.kestra.plugin.slack.notifications.SlackIncomingWebhook
        url: "{{ secrets('SLACK_WEBHOOK_URL')}}"
        payload: "{{inputs.message}}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ envs.webhook_id)}}"
