global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Job Redpanda (Indispensable pour le dashboard 18135)
  - job_name: 'redpanda'
    metrics_path: '/public_metrics'
    static_configs:
      - targets: ['redpanda:9644']

  # 2. Job Kestra
  - job_name: 'kestra'
    metrics_path: '/metrics'
    fallback_scrape_protocol: 'PrometheusText1.0.0'
    static_configs:
      - targets: ['kestra:8081']

  # 3. Job Spark (Générique)
  - job_name: 'spark-master'
    metrics_path: '/metrics/json'  # ← Chemin MASTER spécifique
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'spark-executors'
    metrics_path: '/metrics/executors/json'
    static_configs:
      - targets: ['spark-master:8080']
